# Generated by Django 4.2.19 on 2025-02-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название аниме')),
                ('rank', models.IntegerField(verbose_name='Рейтинг')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('release_year', models.IntegerField(verbose_name='Год выхода')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название манги')),
                ('rank', models.IntegerField(verbose_name='Рейтинг')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('release_year', models.IntegerField(verbose_name='Год выпуска')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
    ]
